/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.decimal.pixel.entity;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Customers extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5444115032788277205L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Customers\",\"namespace\":\"com.decimal.pixel.entity\",\"fields\":[{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"contactPhone\",\"type\":\"string\"},{\"name\":\"contactEmail\",\"type\":\"string\"}],\"connect.name\":\"com.decimal.pixel.entity.Customers\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Customers> ENCODER =
      new BinaryMessageEncoder<Customers>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Customers> DECODER =
      new BinaryMessageDecoder<Customers>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Customers> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Customers> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Customers>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Customers to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Customers from a ByteBuffer. */
  public static Customers fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence firstName;
  @Deprecated public java.lang.CharSequence lastName;
  @Deprecated public java.lang.CharSequence contactPhone;
  @Deprecated public java.lang.CharSequence contactEmail;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Customers() {}

  /**
   * All-args constructor.
   * @param firstName The new value for firstName
   * @param lastName The new value for lastName
   * @param contactPhone The new value for contactPhone
   * @param contactEmail The new value for contactEmail
   */
  public Customers(java.lang.CharSequence firstName, java.lang.CharSequence lastName, java.lang.CharSequence contactPhone, java.lang.CharSequence contactEmail) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.contactPhone = contactPhone;
    this.contactEmail = contactEmail;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return firstName;
    case 1: return lastName;
    case 2: return contactPhone;
    case 3: return contactEmail;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: firstName = (java.lang.CharSequence)value$; break;
    case 1: lastName = (java.lang.CharSequence)value$; break;
    case 2: contactPhone = (java.lang.CharSequence)value$; break;
    case 3: contactEmail = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'firstName' field.
   * @return The value of the 'firstName' field.
   */
  public java.lang.CharSequence getFirstName() {
    return firstName;
  }

  /**
   * Sets the value of the 'firstName' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the 'lastName' field.
   * @return The value of the 'lastName' field.
   */
  public java.lang.CharSequence getLastName() {
    return lastName;
  }

  /**
   * Sets the value of the 'lastName' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the 'contactPhone' field.
   * @return The value of the 'contactPhone' field.
   */
  public java.lang.CharSequence getContactPhone() {
    return contactPhone;
  }

  /**
   * Sets the value of the 'contactPhone' field.
   * @param value the value to set.
   */
  public void setContactPhone(java.lang.CharSequence value) {
    this.contactPhone = value;
  }

  /**
   * Gets the value of the 'contactEmail' field.
   * @return The value of the 'contactEmail' field.
   */
  public java.lang.CharSequence getContactEmail() {
    return contactEmail;
  }

  /**
   * Sets the value of the 'contactEmail' field.
   * @param value the value to set.
   */
  public void setContactEmail(java.lang.CharSequence value) {
    this.contactEmail = value;
  }

  /**
   * Creates a new Customers RecordBuilder.
   * @return A new Customers RecordBuilder
   */
  public static com.decimal.pixel.entity.Customers.Builder newBuilder() {
    return new com.decimal.pixel.entity.Customers.Builder();
  }

  /**
   * Creates a new Customers RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Customers RecordBuilder
   */
  public static com.decimal.pixel.entity.Customers.Builder newBuilder(com.decimal.pixel.entity.Customers.Builder other) {
    return new com.decimal.pixel.entity.Customers.Builder(other);
  }

  /**
   * Creates a new Customers RecordBuilder by copying an existing Customers instance.
   * @param other The existing instance to copy.
   * @return A new Customers RecordBuilder
   */
  public static com.decimal.pixel.entity.Customers.Builder newBuilder(com.decimal.pixel.entity.Customers other) {
    return new com.decimal.pixel.entity.Customers.Builder(other);
  }

  /**
   * RecordBuilder for Customers instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Customers>
    implements org.apache.avro.data.RecordBuilder<Customers> {

    private java.lang.CharSequence firstName;
    private java.lang.CharSequence lastName;
    private java.lang.CharSequence contactPhone;
    private java.lang.CharSequence contactEmail;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.decimal.pixel.entity.Customers.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.firstName)) {
        this.firstName = data().deepCopy(fields()[0].schema(), other.firstName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lastName)) {
        this.lastName = data().deepCopy(fields()[1].schema(), other.lastName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.contactPhone)) {
        this.contactPhone = data().deepCopy(fields()[2].schema(), other.contactPhone);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.contactEmail)) {
        this.contactEmail = data().deepCopy(fields()[3].schema(), other.contactEmail);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Customers instance
     * @param other The existing instance to copy.
     */
    private Builder(com.decimal.pixel.entity.Customers other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.firstName)) {
        this.firstName = data().deepCopy(fields()[0].schema(), other.firstName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lastName)) {
        this.lastName = data().deepCopy(fields()[1].schema(), other.lastName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.contactPhone)) {
        this.contactPhone = data().deepCopy(fields()[2].schema(), other.contactPhone);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.contactEmail)) {
        this.contactEmail = data().deepCopy(fields()[3].schema(), other.contactEmail);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'firstName' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirstName() {
      return firstName;
    }

    /**
      * Sets the value of the 'firstName' field.
      * @param value The value of 'firstName'.
      * @return This builder.
      */
    public com.decimal.pixel.entity.Customers.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.firstName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'firstName' field has been set.
      * @return True if the 'firstName' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'firstName' field.
      * @return This builder.
      */
    public com.decimal.pixel.entity.Customers.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastName' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastName() {
      return lastName;
    }

    /**
      * Sets the value of the 'lastName' field.
      * @param value The value of 'lastName'.
      * @return This builder.
      */
    public com.decimal.pixel.entity.Customers.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.lastName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'lastName' field has been set.
      * @return True if the 'lastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'lastName' field.
      * @return This builder.
      */
    public com.decimal.pixel.entity.Customers.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'contactPhone' field.
      * @return The value.
      */
    public java.lang.CharSequence getContactPhone() {
      return contactPhone;
    }

    /**
      * Sets the value of the 'contactPhone' field.
      * @param value The value of 'contactPhone'.
      * @return This builder.
      */
    public com.decimal.pixel.entity.Customers.Builder setContactPhone(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.contactPhone = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'contactPhone' field has been set.
      * @return True if the 'contactPhone' field has been set, false otherwise.
      */
    public boolean hasContactPhone() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'contactPhone' field.
      * @return This builder.
      */
    public com.decimal.pixel.entity.Customers.Builder clearContactPhone() {
      contactPhone = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'contactEmail' field.
      * @return The value.
      */
    public java.lang.CharSequence getContactEmail() {
      return contactEmail;
    }

    /**
      * Sets the value of the 'contactEmail' field.
      * @param value The value of 'contactEmail'.
      * @return This builder.
      */
    public com.decimal.pixel.entity.Customers.Builder setContactEmail(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.contactEmail = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'contactEmail' field has been set.
      * @return True if the 'contactEmail' field has been set, false otherwise.
      */
    public boolean hasContactEmail() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'contactEmail' field.
      * @return This builder.
      */
    public com.decimal.pixel.entity.Customers.Builder clearContactEmail() {
      contactEmail = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Customers build() {
      try {
        Customers record = new Customers();
        record.firstName = fieldSetFlags()[0] ? this.firstName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.lastName = fieldSetFlags()[1] ? this.lastName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.contactPhone = fieldSetFlags()[2] ? this.contactPhone : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.contactEmail = fieldSetFlags()[3] ? this.contactEmail : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Customers>
    WRITER$ = (org.apache.avro.io.DatumWriter<Customers>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Customers>
    READER$ = (org.apache.avro.io.DatumReader<Customers>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
